javac -d . Sound.java
javac -d . BouttonPlay.java
javac -d . BouttonStop.java
javac -d . BouttonPause.java
javac -d . BouttonFolder.java
javac -d . BouttonPrevious.java
javac -d . BouttonNext.java
javac -d . MenuTotal.java
javac -d . IcoErreur.java
javac -d . InfoErreur.java
javac -d . Chanson.java
javac -d . Playlist.java
javac -d . PlayListener.java
javac -d . StopListener.java
javac -d . PauseListener.java
javac -d . PreviousListener.java
javac -d . NextListener.java
javac -d . Lecturemp3Listener.java
javac -d . FolderListener.java
javac -d . Completeinfo.java
javac -d . CompleteinfoListener.java
javac -d . QuitListener.java
javac -d . PlaylistListener.java
javac -d . GestionListener.java
javac -d . GestionListener2.java
javac -d . FenetrePlaylist.java
javac -d . FenetrePlaylist2.java
javac -d . TimerListener.java
javac -d . MesTaches.java
javac -d . MonTimerTask.java
javac -d . Interface.java
javac -d . FermetureListener.java
javac -d . Lanceur.java
java mp3.Lanceur
pause